### ISSUE TITLE
Fails to build on Ubuntu 14.10

### ISSUE THREAD

**Issue by hotice** [pyamsoft/pstate-frequency#3]
I'm running Ubuntu 14.10 64bit and pstate-frequency fails to build for me. Here's the complete log:

```
CFLAGS  =  -DDEBUG=0 -DVERSION="0.r.46.eb0ad58[cc]" -std=c99 -O2 -Wall -Wextra -Werror -Wmissing-prototypes -Wunreachable-code -I.
LDFLAGS =  -Wl,-O2,--sort-common,--as-needed,-z,relro,-s
CC      =  cc
cc -c src/mhz.c -o obj/mhz.o
cc -c src/cpu.c -o obj/cpu.o
cc -c src/main.c -o obj/main.o
src/cpu.c: In function ‘pyam_cpu_internal_get’:
src/cpu.c:365:5: error: ignoring return value of ‘getline’, declared with attribute warn_unused_result [-Werror=unused-result]
     getline(&line, &n, file);
     ^
src/cpu.c: In function ‘pyam_cpu_get_file_contents_str’:
src/cpu.c:96:5: error: ignoring return value of ‘getline’, declared with attribute warn_unused_result [-Werror=unused-result]
     getline(&line, &n, file);
     ^
src/cpu.c: In function ‘pyam_cpu_get_number’:
src/cpu.c:119:9: error: ignoring return value of ‘system’, declared with attribute warn_unused_result [-Werror=unused-result]
         system(command);
         ^
src/cpu.c:120:9: error: ignoring return value of ‘system’, declared with attribute warn_unused_result [-Werror=unused-result]
         system(readable);
         ^
cc1: all warnings being treated as errors
Makefile:23: recipe for target 'obj/cpu.o' failed
make: *** [obj/cpu.o] Error 1
make: *** Waiting for unfinished jobs....
```
